### ISSUE TITLE
How to classify PNG?

### ISSUE THREAD

**Issue by wunamesst** [infinitered/nsfwjs#274]
Hello, I tried to classify a png image in nodejs, but it throws an exception: Size (357604) must match the product of 1,299,299,3 shapes. 
How can this be resolved?

**Comment by GantMan** [comment]
I assume you were trying to classify on node?

**Comment by wunamesst** [comment]
> I assume you were trying to classify on node?
> 
> Have you looked at how to convert a PNG to a tensor? https://stackoverflow.com/questions/53231699/converting-png-to-tensor-tensorflow-js

----------------------
@GantMan Thank you very much for your reply, this issue has been resolved.

I am now experiencing another problem. I trained a batch of images with **nsfw_model / train_all_model.sh** (using https://tfhub.dev/google/imagenet/mobilenet_v2_140_224/classification/4) and then I used tensorflowjs- The converter converted from **keras** or **keras_saved_model** to **tfjs_layer_model** and succeeded. But when I reference the model in nsfwjs-node, I get an error message:

```
2020-04-02 15:45:40,085 ERROR 70582 nodejs.unhandledRejectionError: Unknown layer: KerasLayer. This may be due to one of the following reasons:
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
1. The layer is defined in Python, in which case it needs to be ported to TensorFlow.js or your JavaScript code.
2. The custom layer is defined in JavaScript, but is not registered properly with tf.serialization.registerClass().
    at new ValueError (/Users/wuguofeng/www/nodejs/classify/node_modules/nsfwjs-node/node_modules/@tensorflow/tfjs-layers/dist/errors.js:68:28)
    at Object.deserializeKerasObject (/Users/wuguofeng/www/nodejs/classify/node_modules/nsfwjs-node/node_modules/@tensorflow/tfjs-layers/dist/utils/generic_utils.js:260:19)
    at Object.deserialize (/Users/wuguofeng/www/nodejs/classify/node_modules/nsfwjs-node/node_modules/@tensorflow/tfjs-layers/dist/layers/serialization.js:29:28)
    at Sequential.fromConfig (/Users/wuguofeng/www/nodejs/classify/node_modules/nsfwjs-node/node_modules/@tensorflow/tfjs-layers/dist/models.js:958:41)
    at Object.deserializeKerasObject (/Users/wuguofeng/www/nodejs/classify/node_modules/nsfwjs-node/node_modules/@tensorflow/tfjs-layers/dist/utils/generic_utils.js:294:29)
    at Object.deserialize (/Users/wuguofeng/www/nodejs/classify/node_modules/nsfwjs-node/node_modules/@tensorflow/tfjs-layers/dist/layers/serialization.js:29:28)
    at /Users/wuguofeng/www/nodejs/classify/node_modules/nsfwjs-node/node_modules/@tensorflow/tfjs-layers/dist/models.js:290:45
    at step (/Users/wuguofeng/www/nodejs/classify/node_modules/nsfwjs-node/node_modules/@tensorflow/tfjs-layers/dist/models.js:54:23)
    at Object.next (/Users/wuguofeng/www/nodejs/classify/node_modules/nsfwjs-node/node_modules/@tensorflow/tfjs-layers/dist/models.js:35:53)
    at fulfilled (/Users/wuguofeng/www/nodejs/classify/node_modules/nsfwjs-node/node_modules/@tensorflow/tfjs-layers/dist/models.js:26:58)
name: "unhandledRejectionError"
pid: 70582
hostname: bogon
```

How should I train the models that nsfwjs-node can use?
Looking forward to your reply, thank you again!
