### ISSUE TITLE
trying to implement nsfwjs model in flutter web but getting same number from predicted array 

### ISSUE THREAD

**Issue by anand654** [infinitered/nsfwjs#489]
label : help needed 

i am trying to use this nsfwjs model in flutter web by taking reference from this repo
github link : https://github.com/AseemWangoo/experiments_with_webtree/master/lib/ml

in this example the  mobilenet model is working fine,
so i tried to implement this code to nsfwjs model 

 added these script tag
      <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.3.0/dist/tf.min.js"></script>
      <script src="https://unpkg.com/nsfwjs@2.3.0/dist/nsfwjs.min.js"></script>

the closest i got from the below javascript code is

`async function nsfwImageFilter() {
const img = document.getElementById('img');
let result = [];
const model = await tf.loadLayersModel('assets/model.json');
    const pixel = tf.browser.fromPixels(img)
    const resized = tf.image.resizeBilinear(pixel,[299,299])
    const casted = resized.cast('int32')
    const expanded = casted.expandDims(0)

const predictions= await model.predict(expanded).data();

for(var i = 0; i < predictions.length ; i++){
        console.log(predictions[i])
        result.push(predictions[i]);
    }
 return result;
}`

output : [2.982787221427266e-14, 2.053509825745257e-30, 1, 0, 0]

pls help me understand where i am doing it wrong , because for every image the 3rd number of this array is always 1 or ~1

**Comment by GantMan** [comment]
That's strange that it keeps thinking the right model is the 3rd option.

Which model are you using?  The 299x299 I see.   Have you tried the 224x224 model?

Also, why are you bringing in NSFWJS if you're writing the model.predict code yourself?

**Comment by anand654** [comment]
i am really sorry for 11 days late ,

```Error: Error: layer: Improper config format: {"node":[{"name":"input","op":"Placeholder","attr":{"shape":{"shape":{"dim":[{"size":"-1"},{"size":"224"},{"size":"224"},{"size":"3"}]}},"dtype":{"type":"DTFLOAT"}}},
.
.
.
'className' and 'config' must set.
    at Object.createErrorWithStack (http://localhost:58507/dart_sdk.js:5362:12)
    at Object._rethrow (http://localhost:58507/dart_sdk.js:39503:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:58507/dart_sdk.js:39497:13)
    at Object._microtaskLoop (http://localhost:58507/dart_sdk.js:39329:13)
    at _startMicrotaskLoop (http://localhost:58507/dart_sdk.js:39335:13)
    at http://localhost:58507/dart_sdk.js:34842:9
```

this is the error when i tried with 224x224 model

**Comment by anand654** [comment]
iam sorry for not writing a reply for 11 days,

but nsfwjs tflite model is working great,
so i decided to move my project from flutter web to flutter android & ios applications

this is the error iam getting when i use 224*224 model 


```
Error: Error: layer: Improper config format: {"node":[{"name":"input","op":"Placeholder","attr":{"shape":{"shape":{"dim":[{"size":"-1"},{"size":"224"},{"size":"224"},{"size":"3"}]}},"dtype":{"type":"DTFLOAT"}}}
.
.
.
'className' and 'config' must set.
```

**Comment by anand654** [comment]
iam sorry for not writing a reply for 11 days,

but nsfwjs tflite model is working great,
so i moved my project from flutter web to flutter android & ios applications

this is the error iam getting when i use 224*224 model

```
Error: Error: layer: Improper config format: {"node":[{"name":"input","op":"Placeholder","attr":{"shape":{"shape":{"dim":[{"size":"-1"},{"size":"224"},{"size":"224"},{"size":"3"}]}},"dtype":{"type":"DTFLOAT"}}}
.
.
.
'className' and 'config' must set.
```
