### ISSUE TITLE
How do i install @tensorflow/tfjs-node with cpu-linux-arm64?

### ISSUE THREAD

**Issue by DevCarnage** [infinitered/nsfwjs#603]
```
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! CPU-linux-3.15.0.tar.gz
npm ERR! * Downloading libtensorflow
npm ERR! /home/ubuntu/bot/NSFW-Detection-bot/node_modules/@tensorflow/tfjs-node/scripts/install.js:106
npm ERR!     throw new Error(`Unsupported system: ${libType}-${platform}-${os.arch()}`);
npm ERR!           ^
npm ERR!
npm ERR! Error: Unsupported system: cpu-linux-arm64
npm ERR!     at getPlatformLibtensorflowUri (/home/ubuntu/bot/NSFW-Detection-bot/node_modules/@tensorflow/tfjs-node/scripts/install.js:106:11)
npm ERR!     at downloadLibtensorflow (/home/ubuntu/bot/NSFW-Detection-bot/node_modules/@tensorflow/tfjs-node/scripts/install.js:139:15)
npm ERR!     at async run (/home/ubuntu/bot/NSFW-Detection-bot/node_modules/@tensorflow/tfjs-node/scripts/install.js:208:5)
```
Command i used "npm i @tensorflow/tfjs-node" and my OS is Ubuntu

**Comment by DevCarnage** [comment]
Just going to close this issue because i realized the issue was with another NPM and not really an issue in here.
