### ISSUE TITLE
Error on vite.js `Cannot read properties of undefined (reading 'listenerCount')`

### ISSUE THREAD

**Issue by arifszn** [infinitered/nsfwjs#626]
I am trying to use this project on [ vite.js](https://vitejs.dev/) as a react project.

The code:
```jsx
import React, { useEffect } from 'react';
import * as nsfwjs from 'nsfwjs';

export default function App() {
  useEffect(() => {
    nsfwjs.load().then((model) => {
      console.info('loaded');
    });
  }, []);

  return <div>Hello</div>;
}
```

But the model is not being loaded and throwing error. I have also tried to load the model from local folder.

```
_stream_readable.js:38 Uncaught TypeError: Cannot read properties of undefined (reading 'listenerCount')
    at node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:38:9)
    at __require (chunk-QOVRSCHT.js?v=01dd7285:11:50)
    at node_modules/readable-stream/readable.js (readable.js:1:28)
    at __require (chunk-QOVRSCHT.js?v=01dd7285:11:50)
    at node_modules/gif-encoder/lib/GIFEncoder.js (GIFEncoder.js:13:22)
    at __require (chunk-QOVRSCHT.js?v=01dd7285:11:50)
    at node_modules/@nsfw-filter/save-pixels/save-pixels.js (save-pixels.js:3:18)
    at __require (chunk-QOVRSCHT.js?v=01dd7285:11:50)
    at node_modules/@nsfw-filter/gif-frames/gif-frames.js (gif-frames.js:3:18)
    at __require (chunk-QOVRSCHT.js?v=01dd7285:11:50)
```
![image](https://user-images.githubusercontent.com/45073703/173242389-deb54879-be8a-451b-ba30-e47966703413.png)

**Comment by ene5135** [comment]
Any progress about this? I got same problem with vite.js 😥

**Comment by arifszn** [comment]
ping @infinitered

**Comment by GantMan** [comment]
This library depends on node-polyfills it seems.  Vite has this issue with a few libraries it seems.

I've seen documentation of people using `overrides` or `resolutions` in their package.json files to tell vite what to keep, and I've also seen "NodeModulesPolyfillPlugin" imported as well.

I hope that helps.  I'm not terribly familiar with vite.

**Comment by Melak12** [comment]
I have the same issue. No solution yet?

**Comment by cdanwards** [comment]
@arifszn @Melak12 I was able to find a potential fix for this issue:

Similar to the issue described `[here](https://github.com/vitejs/vite/discussions/7938#discussioncomment-2657764)`, if you use the prebundled `nsfwjs` script it seems to workaround the problem. In the `vite.config.ts`:
``` vite.config.ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
      alias: [
      {
        find: 'nsfwjs',
        replacement: 'nsfwjs/dist/nsfwjs.min.js',
      },
    ],
  }
})
```

**Comment by hololb** [comment]
Had this problem too, found this Vite plugin to be useful and it's cleared up my errors.
https://www.npmjs.com/package/vite-plugin-node-polyfills
