### ISSUE TITLE
Failed to load model from local (nodejs)

### ISSUE THREAD

**Issue by sakurazumii** [infinitered/nsfwjs#689]
Greetings. As the title have said, I am clueless about how to load a local model. More details below.

Here is my codebase:   
```js
global.model = null
async function loadModel() {
    const loadfrom = 'file://' + __dirname.replace(/\\/g, '/') + '/mobilenet_v2_140_224/web_model/'
    console.log(loadfrom)
    const tf = require('@tensorflow/tfjs-node')
    const nsfw = require('nsfwjs')
    model = await nsfw.load(loadfrom, { type: 'graph' })
}
loadModel()
```
(Ignore the regex, it only changes "\" to "/" because I'm on a Windows machine. removing that produces the same error)

Console output:
```bash
file://C:/Users/sakurazumii/Desktop/demo/mobilenet_v2_140_224/web_model/
C:\Users\sakurazumii\Desktop\demo\node_modules\node-fetch\lib\index.js:1327
                throw new TypeError('Only absolute URLs are supported');
                      ^

TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Users\sakurazumii\Desktop\demo\node_modules\node-fetch\lib\index.js:1327:9)
    at C:\Users\sakurazumii\Desktop\demo\node_modules\node-fetch\lib\index.js:1440:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\sakurazumii\Desktop\demo\node_modules\node-fetch\lib\index.js:1437:9)
    at HTTPRequest.PlatformNode.fetch (C:\Users\sakurazumii\Desktop\demo\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:7430:16)
    at HTTPRequest.<anonymous> (C:\Users\sakurazumii\Desktop\demo\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:8289:55)
    at step (C:\Users\sakurazumii\Desktop\demo\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:125:27)
    at Object.next (C:\Users\sakurazumii\Desktop\demo\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:74:53)
    at C:\Users\sakurazumii\Desktop\demo\node_modules\@tensorflow\tfjs-core\dist\tf-core.node.js:67:71
    at new Promise (<anonymous>)
```

It happens with **both** with and without the `file://` prefix.

Interestingly, if I put in a relative path that is the same format with the one in [Node.js app demo on this repo readme](https://github.com/infinitered/nsfwjs/#node-js-app):
`file:// ./mobilenet_v2_140_224/web_model/`, it threw out `TypeError [ERR_INVALID_URL]: Invalid URL`. 

**Paths I have tried**:
`file://./mobilenet_v2_140_224/web_model/` (removed space) => `TypeError: Only HTTP(S) protocols are supported`
`file:///mobilenet_v2_140_224/web_model/` => `TypeError: Only absolute URLs are supported`
`./mobilenet_v2_140_224/web_model/` => `TypeError: Only absolute URLs are supported`
`/mobilenet_v2_140_224/web_model/` => `TypeError: Only absolute URLs are supported`

Both issues I have found related to locally loading the model are still open to this day: #512 #522 #652

**Models I have used:**
https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/quant_mid
https://github.com/GantMan/nsfw_model/releases/tag/1.1.0

Am I doing something wrong or the documentation is obsecure that I couldn't find anything? Calling `load()` loads the default model which turns out predicts images differently than the models on nsfwjs.com. 

Any help would be greatly appricieated.

**Comment by cdanwards** [comment]
@scarletzumii sorry that you're experiencing this outstanding bug. We're taking some time to look into it!

**Comment by huhm** [comment]
overide the load function  ,and post fetchFunc option to tf.loadLayersModel/tf.loadGraphModel

**Comment by sonofmagic** [comment]
I meet the same issue. I download the latest `nsfw_model` from [`GantMan/nsfw_model`](https://github.com/GantMan/nsfw_model)'s [releases page](https://github.com/GantMan/nsfw_model/releases). 

And fail to load layer model `web_model` or `web_model_quantized`. 

Would you provide a example which loads local model ? Thanks.

**Comment by xxaier** [comment]
![image](https://user-images.githubusercontent.com/130831741/234793381-bfffea96-80a4-4d6b-b86a-e7350f1afae2.png)


```
var bin, img, model_fp, nsfw;

import ROOT from './ROOT';

import {
  join
} from 'path';

import {
  NSFWJS
} from 'nsfwjs';

import tf from '@tensorflow/tfjs-node';

await tf.enableProdMode();

await tf.ready();

model_fp = 'file://' + join(ROOT, 'model/quant_mid/model.json');

nsfw = new NSFWJS(model_fp, {
  size: 224
});

nsfw.load = async function() {
  this.model = (await tf.loadGraphModel(model_fp));
};

await nsfw.load();

console.log(nsfw.classify);

import {
  readFileSync
} from 'fs';

img = readFileSync('/Users/z/art/pkg/bot/adult/out/9/0.png');

bin = tf.node.decodeImage(img, 3);

console.log((await nsfw.classify(bin)));

bin.dispose();
```

**Comment by JemiloII** [comment]
None of these work without actually sending a request. I don't want to send any requests. Any better way to load this without node-fetch or better yet, maybe use torch instead of tensorflow?

**Comment by GantMan** [comment]
Is there a good torch for JS solution?

**Comment by miaoihan** [comment]
And? Is there no one to solve the problem?

**Comment by GantMan** [comment]
We're nearing a sprint to make NSFWJS work well on mobile.

If we have the time/resources we'll come back and look at this.  It would be great if someone who figures it out to post their solution.
