### ISSUE TITLE
Getting Uncaught ReferenceError when using nsfwjs.load()

### ISSUE THREAD

**Issue by talisraeli** [infinitered/nsfwjs#762]
I'm getting an error of process is not defined when using `nsfwjs.load("/model/", { size: 299 })` on my ReactJS app.
Seems to be an error in the library... (version: 2.4.2)
It doesn't change the error message if I change the function parameters.

```
util.js:109 Uncaught ReferenceError: process is not defined
    at node_modules/util/util.js (util.js:109:1)
    at __require2 (chunk-TFWDKVI3.js?v=166c4fc5:18:50)
    at node_modules/assert/build/internal/assert/assertion_error.js (assertion_error.js:35:16)
    at __require2 (chunk-TFWDKVI3.js?v=166c4fc5:18:50)
    at node_modules/assert/build/assert.js (assert.js:36:22)
    at __require2 (chunk-TFWDKVI3.js?v=166c4fc5:18:50)
    at node_modules/gif-encoder/lib/GIFEncoder.js (GIFEncoder.js:11:14)
    at __require2 (chunk-TFWDKVI3.js?v=166c4fc5:18:50)
    at node_modules/@nsfw-filter/save-pixels/save-pixels.js (save-pixels.js:3:18)
    at __require2 (chunk-TFWDKVI3.js?v=166c4fc5:18:50)
node_modules/util/util.js @ util.js:109
__require2 @ chunk-TFWDKVI3.js?v=166c4fc5:18
node_modules/assert/build/internal/assert/assertion_error.js @ assertion_error.js:35
__require2 @ chunk-TFWDKVI3.js?v=166c4fc5:18
node_modules/assert/build/assert.js @ assert.js:36
__require2 @ chunk-TFWDKVI3.js?v=166c4fc5:18
node_modules/gif-encoder/lib/GIFEncoder.js @ GIFEncoder.js:11
__require2 @ chunk-TFWDKVI3.js?v=166c4fc5:18
node_modules/@nsfw-filter/save-pixels/save-pixels.js @ save-pixels.js:3
__require2 @ chunk-TFWDKVI3.js?v=166c4fc5:18
node_modules/@nsfw-filter/gif-frames/gif-frames.js @ gif-frames.js:3
__require2 @ chunk-TFWDKVI3.js?v=166c4fc5:18
node_modules/nsfwjs/dist/index.js @ index.js:64
__require2 @ chunk-TFWDKVI3.js?v=166c4fc5:18
(anonymous) @ index.js:301
```

**Comment by talisraeli** [comment]
This error message isn't shown anymore if I define these configurations in `vite.config.ts`:
```typescript
define: {
    "process.env.NODE_DEBUG": false,
    Buffer: ["buffer", "Buffer"],
},
``` 

But now, this error is shown:
```
inherits_browser.js:6 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.create (<anonymous>)
    at Object.inherits (inherits_browser.js:6:31)
    at node_modules/gif-encoder/node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:63:6)
    at __require2 (chunk-TFWDKVI3.js?v=ea788f6a:18:50)
    at node_modules/gif-encoder/node_modules/readable-stream/readable.js (readable.js:1:28)
    at __require2 (chunk-TFWDKVI3.js?v=ea788f6a:18:50)
    at node_modules/gif-encoder/lib/GIFEncoder.js (GIFEncoder.js:13:22)
    at __require2 (chunk-TFWDKVI3.js?v=ea788f6a:18:50)
    at node_modules/@nsfw-filter/save-pixels/save-pixels.js (save-pixels.js:3:18)
    at __require2 (chunk-TFWDKVI3.js?v=ea788f6a:18:50)
inherits @ inherits_browser.js:6
node_modules/gif-encoder/node_modules/readable-stream/lib/_stream_readable.js @ _stream_readable.js:63
__require2 @ chunk-TFWDKVI3.js?v=ea788f6a:18
node_modules/gif-encoder/node_modules/readable-stream/readable.js @ readable.js:1
__require2 @ chunk-TFWDKVI3.js?v=ea788f6a:18
node_modules/gif-encoder/lib/GIFEncoder.js @ GIFEncoder.js:13
__require2 @ chunk-TFWDKVI3.js?v=ea788f6a:18
node_modules/@nsfw-filter/save-pixels/save-pixels.js @ save-pixels.js:3
__require2 @ chunk-TFWDKVI3.js?v=ea788f6a:18
node_modules/@nsfw-filter/gif-frames/gif-frames.js @ gif-frames.js:3
__require2 @ chunk-TFWDKVI3.js?v=ea788f6a:18
node_modules/nsfwjs/dist/index.js @ index.js:64
__require2 @ chunk-TFWDKVI3.js?v=ea788f6a:18
(anonymous) @ index.js:301
```
