### ISSUE TITLE
Cant import nsfw in react Project 

### ISSUE THREAD

**Issue by azr-arch** [infinitered/nsfwjs#788]
having issues with importing 

TypeError: Cannot read properties of undefined (reading 'listenerCount')
    at node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:38:9)
    at __require (chunk-ROME4SDB.js?v=ea232646:11:50)
    at node_modules/readable-stream/readable.js (readable.js:1:28)
    at __require (chunk-ROME4SDB.js?v=ea232646:11:50)
    at node_modules/gif-encoder/lib/GIFEncoder.js (GIFEncoder.js:13:22)
    at __require (chunk-ROME4SDB.js?v=ea232646:11:50)
    at node_modules/@nsfw-filter/save-pixels/save-pixels.js (save-pixels.js:3:18)
    at __require (chunk-ROME4SDB.js?v=ea232646:11:50)
    at node_modules/@nsfw-filter/gif-frames/gif-frames.js (gif-frames.js:3:18)
    at __require (chunk-ROME4SDB.js?v=ea232646:11:50)

**Comment by hubsMIT1** [comment]
Same error for me too

**Comment by hubsMIT1** [comment]
@azr-arch, check the #626 issue
